[package]
name = "tmdb-shelf"
version = "0.1.1"
authors = ["Olivier ROLAND <newca12@users.noreply.github.com>"]
description = "Movie collection manager using TMDb API, built with Iced."
homepage = "https://github.com/newca12/TMDb-shelf"
repository = "https://github.com/newca12/TMDb-shelf.git"
keywords = ["gui", "tmdb", "movie", "imdb", "cli"]
categories = ["gui"]
edition = "2024"
license = "GPL-3.0-or-later"


[dependencies]
iced = { version = "0.14.0", features = ["tokio", "image"] }
iced_aw = { version = "0.13.1", features = ["date_picker"] }
tokio = { version = "1.49.0", features = ["process", "fs"] }
reqwest = { version = "0.13.2", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
toml = "0.9.8"
libsql = "0.9.29"
chrono = { version = "0.4.44", features = ["serde"] }
rfd = "0.17.2"
open = "5.3.3"
dirs = "6.0.0"
image = { version = "0.25", default-features = false, features = ["png"] }
