addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"           % "2.4.2")
addSbtPlugin("org.scoverage"  % "sbt-scoverage"          % "1.8.1")
addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo"          % "0.10.0")
//addSbtPlugin("com.typesafe.sbt" %% "sbt-native-packager"   % "1.3.17")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.15.0")
//addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"           % "0.6.0-M14")
