addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "0.7.0")
addSbtPlugin("org.scalariform" % "sbt-scalariform" % "1.6.0")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.3.3")
addSbtPlugin("no.vedaadata" %% "sbt-javafx" % "0.7")
addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.5.0")
